# Generated by Django 6.0 on 2025-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
