# Generated by Django 6.0 on 2025-12-09 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscription_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('3_days', '3 Days Before'), ('1_day', '1 Day Before')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='billing.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'reminder_type')},
            },
        ),
    ]
