# Generated by Django 6.0 on 2025-12-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_routerdevice_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='speed',
        ),
        migrations.AddField(
            model_name='package',
            name='download_speed',
            field=models.PositiveIntegerField(default=10, help_text='Mbps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='upload_speed',
            field=models.PositiveIntegerField(default=5, help_text='Mbps'),
            preserve_default=False,
        ),
    ]
