# Generated by Django 6.0 on 2025-12-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_package_speed_package_download_speed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
