# Generated by Django 6.0 on 2025-12-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], default='unpaid', max_length=10),
        ),
    ]
