# Generated by Django 6.0 on 2025-12-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
        ),
    ]
