# Generated by Django 6.0 on 2025-12-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerdevice',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
