# Generated by Django 6.0 on 2025-12-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_routerdevice_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerdevice',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerdevice',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='routerdevice',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
