# Generated by Django 6.0 on 2025-12-13 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_routerdevice_is_online_routerdevice_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerdevice',
            name='max_pppoe_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RouterFailoverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='router_down', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
                ('from_router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failovers_from', to='billing.routerdevice')),
                ('to_router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failovers_to', to='billing.routerdevice')),
            ],
        ),
    ]
