# Generated by Django 6.0 on 2025-12-14 01:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_routerdevice_max_pppoe_sessions_routerfailoverlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerfailoverlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failover_logs', to='billing.customer'),
        ),
        migrations.AlterField(
            model_name='routerfailoverlog',
            name='from_router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_from', to='billing.routerdevice'),
        ),
        migrations.AlterField(
            model_name='routerfailoverlog',
            name='reason',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='routerfailoverlog',
            name='to_router',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='failover_to', to='billing.routerdevice'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HotspotUsageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_rx_bytes', models.BigIntegerField(default=0)),
                ('last_tx_bytes', models.BigIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_usage_state', to='billing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PPPoEUsageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_rx_bytes', models.BigIntegerField(default=0)),
                ('last_tx_bytes', models.BigIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_usage_state', to='billing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='HotspotUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_usage_records', to='billing.customer')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.routerdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'period_start'], name='billing_hot_custome_edaf41_idx')],
            },
        ),
        migrations.CreateModel(
            name='PPPoEUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_usage_records', to='billing.customer')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.routerdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'period_start'], name='billing_ppp_custome_8086e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PPPoEUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='billing.customer')),
            ],
            options={
                'unique_together': {('customer', 'date')},
            },
        ),
    ]
