# Generated by Django 6.0 on 2025-12-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_routerfailoverlog_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot')], max_length=10)),
                ('date', models.DateField()),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='billing.customer')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('customer', 'date', 'connection_type')},
            },
        ),
    ]
