# Generated by Django 6.0 on 2025-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_usagerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_data_cap_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='monthly_data_cap_gb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
