# Generated by Django 6.0 on 2025-12-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_customer_custom_data_cap_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pppoe_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
