# Generated by Django 5.2.9 on 2025-12-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_mpesatransaction_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='package',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_value',
            field=models.PositiveIntegerField(default=30, help_text='Number of time units (e.g. 30, 12, 1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='is_hotspot',
            field=models.BooleanField(default=False, help_text='Is this a hotspot-only package?'),
        ),
        migrations.AlterField(
            model_name='package',
            name='monthly_data_cap_gb',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
    ]
