# Generated by Django 5.2.9 on 2025-12-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_remove_package_duration_days_package_duration_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='bound_mac',
            field=models.CharField(blank=True, help_text='MAC address bound on first use', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='first_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
