# Generated by Django 5.2.16 on 2026-07-30 14:43

import billing.models
import django.db.models.deletion
from django.db import migrations, models

# Duplicated from 0026 rather than imported. Migration modules cannot be
# imported by name (they start with a digit) and, more importantly, each
# migration should be self-contained so editing one cannot change another's
# historical behaviour.
SCOPED_MODELS = [
    "RouterDevice", "Customer", "RouterFailoverLog", "Package", "Subscription",
    "Invoice", "Voucher", "Payment", "ExpiryReminderLog", "AccessAuditLog",
    "SystemSetting", "MpesaTransaction", "PPPoEUsageSnapshot",
    "PPPoEUsageState", "PPPoEUsageRecord", "HotspotUsageState",
    "HotspotUsageRecord", "UsageRecord",
]


def assert_no_unclaimed_rows(apps, schema_editor):
    """
    Refuse to add NOT NULL while any row is still unclaimed.

    Postgres would fail on the ALTER anyway, but with a constraint-violation
    message that does not say which table is at fault. This names them, and
    catches rows written between 0026 and this migration by a process still
    running the old code.
    """
    unclaimed = {}
    for model_name in SCOPED_MODELS:
        Model = apps.get_model("billing", model_name)
        n = Model.objects.filter(tenant__isnull=True).count()
        if n:
            unclaimed[model_name] = n

    if unclaimed:
        detail = ", ".join(f"{k}={v}" for k, v in sorted(unclaimed.items()))
        raise RuntimeError(
            "Cannot apply NOT NULL: rows without a tenant remain "
            f"({detail}). Re-run migration 0026, then apply this again."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_backfill_default_tenant'),
    ]

    operations = [
        migrations.RunPython(
            assert_no_unclaimed_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='accessauditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='expiryreminderlog',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='hotspotusagerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='hotspotusagestate',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='package',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='pppoeusagerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='pppoeusagesnapshot',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='pppoeusagestate',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='routerdevice',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='routerfailoverlog',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='tenant',
            field=models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant'),
        ),
    ]
