# Generated by Django 5.2.16 on 2026-07-30 14:51

from django.db import migrations, models
from django.db.models import Count


def assert_no_duplicate_pppoe_usernames(apps, schema_editor):
    """
    Refuse to add the PPPoE uniqueness constraint while duplicates exist.

    Uniqueness was previously enforced only by a race-prone .exists() check in
    generate_pppoe_credentials(), with no database constraint, so duplicates are
    possible in older data.

    Deliberately NOT auto-resolved. A PPPoE username is the key of a live
    `ppp secret` on the MikroTik: rewriting or blanking one here would orphan
    the router entry and drop that customer's connection. Which duplicate is
    genuine is an operational decision, so this reports and stops.
    """
    Customer = apps.get_model("billing", "Customer")

    dupes = (
        Customer.objects
        .exclude(pppoe_username="")
        .values("tenant_id", "pppoe_username")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .order_by("-n")
    )
    dupes = list(dupes)
    if not dupes:
        return

    lines = []
    for row in dupes[:20]:
        ids = list(
            Customer.objects
            .filter(tenant_id=row["tenant_id"], pppoe_username=row["pppoe_username"])
            .values_list("id", flat=True)
        )
        lines.append(f"    {row['pppoe_username']!r} x{row['n']} -> customer ids {ids}")

    more = "" if len(dupes) <= 20 else f"\n    ... and {len(dupes) - 20} more"
    raise RuntimeError(
        "Cannot add customer_tenant_pppoe_username_uniq: duplicate PPPoE "
        "usernames exist.\n"
        + "\n".join(lines) + more
        + "\n\n  Resolve manually — each duplicate maps to a live `ppp secret` on a\n"
          "  router, so choose which customer keeps the username and re-provision\n"
          "  the other before re-running this migration."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_tenant_not_null'),
    ]

    operations = [
        migrations.RunPython(
            assert_no_duplicate_pppoe_usernames,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='customer_hotspot_username_uniq',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('hotspot_username', ''), _negated=True), fields=('tenant', 'hotspot_username'), name='customer_tenant_hotspot_username_uniq'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='customer_tenant_phone_uniq'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('pppoe_username', ''), _negated=True), fields=('tenant', 'pppoe_username'), name='customer_tenant_pppoe_username_uniq'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='systemsetting_tenant_key_uniq'),
        ),
    ]
