# Generated by Django 5.2.16 on 2026-07-30 14:53

from django.db import migrations, models

from billing.db_operations import (
    AddIndexConcurrentlyIfPostgres,
    RemoveIndexConcurrentlyIfPostgres,
)


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction block.
    # Trade-off: a failure part-way leaves this migration partially applied,
    # which is preferable to locking the busiest tables during the rebuild.
    atomic = False

    dependencies = [
        ('billing', '0028_tenant_scoped_uniqueness'),
    ]

    operations = [
        RemoveIndexConcurrentlyIfPostgres(
            model_name='customer',
            name='customer_status_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='customer',
            name='customer_pppoe_username_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='customer',
            name='customer_connection_type_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='invoice',
            name='invoice_payment_status_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='invoice',
            name='invoice_created_at_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='mpesatransaction',
            name='mpesa_status_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='mpesatransaction',
            name='mpesa_processed_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='mpesatransaction',
            name='mpesa_status_processed_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='mpesatransaction',
            name='mpesa_created_at_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='payment',
            name='payment_paid_at_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='payment',
            name='payment_method_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='payment',
            name='payment_paid_at_method_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='subscription',
            name='subscription_status_idx',
        ),
        RemoveIndexConcurrentlyIfPostgres(
            model_name='subscription',
            name='subscription_expiry_date_idx',
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='customer',
            index=models.Index(fields=['tenant', 'status'], name='customer_tenant_status_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='customer',
            index=models.Index(fields=['tenant', 'pppoe_username'], name='customer_tenant_pppoe_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='customer',
            index=models.Index(fields=['tenant', 'connection_type'], name='customer_tenant_conn_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'payment_status'], name='invoice_tenant_status_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'created_at'], name='invoice_tenant_created_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='mpesatransaction',
            index=models.Index(fields=['tenant', 'status'], name='mpesa_tenant_status_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='mpesatransaction',
            index=models.Index(fields=['tenant', 'processed'], name='mpesa_tenant_processed_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='mpesatransaction',
            index=models.Index(fields=['tenant', 'status', 'processed'], name='mpesa_tenant_status_proc_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='mpesatransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='mpesa_tenant_created_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='payment',
            index=models.Index(fields=['tenant', 'paid_at'], name='payment_tenant_paid_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='payment',
            index=models.Index(fields=['tenant', 'method'], name='payment_tenant_method_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='payment',
            index=models.Index(fields=['tenant', 'paid_at', 'method'], name='payment_tenant_paid_method_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'status'], name='sub_tenant_status_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'expiry_date'], name='sub_tenant_expiry_idx'),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'status', 'expiry_date'], name='sub_tenant_status_expiry_idx'),
        ),
    ]
