# Generated by Django 5.2.16 on 2026-07-30 19:01

from django.db import migrations, models


# Old role -> new role.
#
# Deliberately fail-closed: superadmin becomes an *operator* admin, not
# platform staff. Every existing account belongs to the original operator —
# migration 0026 assigned them all to tenant #1 — and promoting one to platform
# staff would silently grant visibility over every future operator. The
# platform owner is created explicitly with `manage.py create_platform_owner`.
ROLE_MAP = {
    "superadmin": "tenant_admin",
    "admin": "tenant_admin",
    "staff": "tenant_staff",
    "customer": "customer",
}


def to_new_roles(apps, schema_editor):
    User = apps.get_model("billing", "User")
    moved = {}
    for old, new in ROLE_MAP.items():
        n = User.objects.filter(role=old).update(role=new)
        if n:
            moved[f"{old}->{new}"] = n

    # Anything unrecognised becomes the least-privileged operator role rather
    # than being left with a value the new constraint would reject.
    stragglers = User.objects.exclude(role__in=set(ROLE_MAP.values())).update(
        role="tenant_staff"
    )
    if stragglers:
        moved["unknown->tenant_staff"] = stragglers

    if moved:
        print("\n  Roles migrated: " + ", ".join(f"{k}={v}" for k, v in moved.items()))


def to_old_roles(apps, schema_editor):
    User = apps.get_model("billing", "User")
    for old, new in ROLE_MAP.items():
        if old == "superadmin":
            continue  # tenant_admin maps back to "admin"; superadmin is lost
        User.objects.filter(role=new).update(role=old)
    # Platform accounts have no pre-migration equivalent.
    User.objects.filter(role__in=("platform_owner", "platform_staff")).update(
        role="admin"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('billing', '0030_row_level_security'),
    ]

    operations = [
        # Must precede AddConstraint: the old role values would violate it.
        migrations.RunPython(to_new_roles, to_old_roles),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_owner', 'Platform Owner'), ('platform_staff', 'Platform Staff'), ('tenant_admin', 'Operator Admin'), ('tenant_staff', 'Operator Staff'), ('customer', 'Customer')], default='tenant_admin', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ('platform_owner', 'platform_staff')), ('tenant__isnull', True)), models.Q(('role__in', ('tenant_admin', 'tenant_staff', 'customer')), ('tenant__isnull', False)), _connector='OR'), name='user_role_matches_tenant_presence'),
        ),
    ]
