# Generated by Django 5.2.16 on 2026-07-30 19:27

import billing.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_platform_and_operator_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', billing.models.BillingUserManager()),
            ],
        ),
    ]
