# Generated by Django 5.2.16 on 2026-07-30 19:35

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Charged to the operator each billing period', max_digits=10)),
                ('billing_period_days', models.PositiveIntegerField(default=30)),
                ('max_customers', models.PositiveIntegerField(default=0)),
                ('max_routers', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('void', 'Void')], default='unpaid', max_length=10)),
                ('due_date', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank'), ('manual', 'Manual')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.tenantinvoice')),
                ('tenant', models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='trialing', max_length=12)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.platformplan')),
                ('tenant', models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.tenantsubscription'),
        ),
        migrations.AddConstraint(
            model_name='tenantsubscription',
            constraint=models.UniqueConstraint(fields=('tenant',), name='one_platform_plan_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantinvoice',
            index=models.Index(fields=['tenant', 'status'], name='tinvoice_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvoice',
            index=models.Index(fields=['status', 'due_date'], name='tinvoice_status_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_start'), name='one_platform_invoice_per_tenant_period'),
        ),
    ]
