# Generated by Django 5.2.16 on 2026-07-31 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_rls_policy_null_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reset_password', 'Reset password'), ('change_password', 'Changed own password'), ('change_username', 'Changed username'), ('create_user', 'Created user'), ('disable_user', 'Disabled user'), ('enable_user', 'Enabled user'), ('change_role', 'Changed role'), ('update_operator', 'Updated operator details')], max_length=32)),
                ('target_label', models.CharField(blank=True, max_length=150)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='billing.tenant')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='adminlog_time_idx'), models.Index(fields=['target_tenant', '-created_at'], name='adminlog_tenant_time_idx')],
            },
        ),
    ]
