# Generated by Django 5.2.16 on 2026-07-31 14:29

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_user_must_change_password_user_token_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('came_online', 'Came online'), ('went_offline', 'Went offline')], max_length=16)),
                ('cause', models.CharField(blank=True, choices=[('unreachable', 'Unreachable'), ('auth_failed', 'Authentication failed'), ('error', 'Error')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='billing.routerdevice')),
                ('tenant', models.ForeignKey(blank=True, default=billing.models.default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['router', '-created_at'], name='revent_router_time_idx'), models.Index(fields=['tenant', '-created_at'], name='revent_tenant_time_idx')],
            },
        ),
    ]
