# Generated by Django 5.2.16 on 2026-07-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_alter_adminactionlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('reset_password', 'Reset password'), ('change_password', 'Changed own password'), ('change_username', 'Changed username'), ('create_user', 'Created user'), ('disable_user', 'Disabled user'), ('enable_user', 'Enabled user'), ('change_role', 'Changed role'), ('update_operator', 'Updated operator details'), ('configure_payments', 'Configured payment credentials'), ('change_plan', 'Changed plan')], max_length=32),
        ),
    ]
