# Generated by Django 5.2.16 on 2026-08-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0058_router_identity_and_unique_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
