# Generated by Django 5.2.16 on 2026-08-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0062_message_log_provider_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionattempt',
            name='outcome',
            field=models.CharField(choices=[('invalid', 'Code not recognised'), ('expired', 'Code has run out of time'), ('device_limit', 'Already on the most devices allowed'), ('blocked', 'Device is blocked'), ('no_provider', 'Portal could not be identified')], max_length=20),
        ),
    ]
