# Generated by Django 5.2.17 on 2026-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0068_data_cap_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerdevice',
            name='active_sessions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routerdevice',
            name='active_sessions_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
