# Generated by Django 5.2.17 on 2026-09-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0069_routerdevice_active_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pppoeusagerecord',
            name='session_restarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pppoeusagerecord',
            name='uptime_seconds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pppoeusagestate',
            name='last_uptime_seconds',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pppoeusagestate',
            name='reconnect_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pppoeusagestate',
            name='total_download_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pppoeusagestate',
            name='total_upload_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pppoeusagestate',
            name='total_uptime_seconds',
            field=models.BigIntegerField(default=0),
        ),
    ]
