# Generated by Django 5.2.17 on 2026-09-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0070_pppoeusagerecord_session_restarted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='data_cap_mb',
            field=models.PositiveIntegerField(blank=True, help_text="Cap in MB as sold. Null inherits the package's current cap.", null=True),
        ),
    ]
